trigger:
  - master
variables:
  - group: DEV

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourceDirectory)\project.json'
    outputType: 'Process'
    orchestratorConnection: 'uipathcommite'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

  